spring:
  application:
    name: mic-consumer-movie
server:
  port: 7901
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.ctoedu.mic.consumer.movie.feign.UserFeignClient: DEBUG